const {createClient}=supabase;const db=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);let editing=null;
const $=id=>document.getElementById(id);function msg(id,t,good=false){$(id).textContent=t;$(id).className="msg "+(good?"good":"");}
async function session(){const {data}=await db.auth.getSession();if(data.session)showDashboard();else showLogin();}
function showLogin(){$("loginBox").style.display="block";$("dashboard").style.display="none";$("logoutBtn").style.display="none";}
async function showDashboard(){$("loginBox").style.display="none";$("dashboard").style.display="block";$("logoutBtn").style.display="inline-block";await listArticles();}
$("loginBtn").onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)msg("loginMsg",error.message);else showDashboard();};
$("logoutBtn").onclick=async()=>{await db.auth.signOut();showLogin();};
$("newBtn").onclick=()=>{editing=null;["title","slug","image","excerpt","content"].forEach(x=>$(x).value="");$("author").value="Redaksi";$("status").value="published";msg("saveMsg","");window.scrollTo({top:0,behavior:"smooth"});};
$("title").oninput=()=>{if(!editing)$("slug").value=$("title").value.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);};
$("saveBtn").onclick=async()=>{const title=$("title").value.trim(),slug=$("slug").value.trim(),category=$("category").value,author=$("author").value.trim()||"Redaksi",excerpt=$("excerpt").value.trim(),content=$("content").value.trim(),status=$("status").value,file=$("image").files[0];if(!title||!slug||!content){msg("saveMsg","Judul, slug, dan isi berita wajib diisi.");return}
let image_url=$("image").dataset.current||null;if(file){const ext=file.name.split(".").pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const up=await db.storage.from("news-images").upload(path,file,{upsert:false});if(up.error){msg("saveMsg",up.error.message);return}image_url=db.storage.from("news-images").getPublicUrl(path).data.publicUrl;}
const row={slug,title,category,author,excerpt,content,image_url,status,published_at:new Date().toISOString(),updated_at:new Date().toISOString()};let res=editing?await db.from("articles").update(row).eq("id",editing):await db.from("articles").insert(row);if(res.error){msg("saveMsg",res.error.message);return}msg("saveMsg","Berita berhasil disimpan.",true);editing=null;await listArticles();};
async function listArticles(){const {data,error}=await db.from("articles").select("*").order("created_at",{ascending:false});if(error){$("articleList").textContent=error.message;return}$("articleList").innerHTML=(data||[]).map(n=>`<div class="admin-item"><div><b>${esc(n.title)}</b><small>${esc(n.category)} • ${esc(n.status)}</small></div><div><button onclick="editArticle('${n.id}')">Edit</button><button onclick="deleteArticle('${n.id}')">Hapus</button></div></div>`).join("")||"Belum ada berita.";}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
window.editArticle=async id=>{const {data}=await db.from("articles").select("*").eq("id",id).single();if(!data)return;editing=id;$("title").value=data.title;$("slug").value=data.slug;$("category").value=data.category;$("author").value=data.author;$("excerpt").value=data.excerpt||"";$("content").value=data.content||"";$("status").value=data.status;$("image").value="";$("image").dataset.current=data.image_url||"";window.scrollTo({top:0,behavior:"smooth"});};
window.deleteArticle=async id=>{if(!confirm("Hapus berita ini?"))return;const {error}=await db.from("articles").delete().eq("id",id);if(error)alert(error.message);else listArticles();};
session();